### PR TITLE
Release/3.2.0

### PR DESCRIPTION
**Pull request by StokesMIDE**
It's been a while, so there are lots of changes:
* command-line utilities have been refactored (#44)
* `StringElement` now treated as strings, not bytes (#50)
* Added `parseSchema()` to read schemata from strings (#53)
* Improved/expanded tests
* Various additional fixes

### CODE REVIEW

**Comment by CFlaniganMide** [comment]
I'd like to remove the travis CI tag, and possibly add something for the github actions.

**Comment by CFlaniganMide** [comment]
> 
> 
> I'd like to remove the travis CI tag, and possibly add something for the github actions.

@StokesMIDE mind if I make a commit for this?

**Comment by StokesMIDE** [comment]
> 
> 
> > I'd like to remove the travis CI tag, and possibly add something for the github actions.
> 
> @StokesMIDE mind if I make a commit for this?

Please do!

**Comment by CrepeGoat** [comment]
@StokesMIDE in the future can you merge the release branch into `dev`, instead of merging `main` into `dev`?

**Comment by StokesMIDE** [comment]
> @StokesMIDE in the future can you merge the release branch into `dev`, instead of merging `main` into `dev`?

That's git-flow.

**Comment by CrepeGoat** [comment]
Actually, merging the release branch into `dev` is the literal gitflow protocol. This is shown in the two gitflow diagrams I linked below.

### From [the Atlassian gitflow article](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), which is referenced in [our git procedures](https://midetech.atlassian.net/wiki/spaces/GE/pages/864354305/GIT)


### From [the original gitflow blogpost](https://nvie.com/posts/a-successful-git-branching-model/) describing the procedure

**Comment by StokesMIDE** [comment]
@CrepeGoat I mean, the merges were literally done by the Sourcetree git-flow extension. I have looked at two other implementations, and it appears they do the merges in the same order. I can imagine one tool getting a standard wrong (like PyCharm not recognizing the `:keyword` docstring tag, or `black` not following PEP-8), but more than one sort of implies it's an accepted (or at least acceptable) practice.

We should take this conversation offline.

**Comment by CrepeGoat** [comment]
okay. yeah it seem like I misunderstood what the tool does. as long as you're using the tool it's all good 👍 thanks for explaining

**Pull request merged**
