### PR TITLE
added test cases for `util.py`

### PR DESCRIPTION
**Pull request by CrepeGoat**
This PR is for adding tests for the script functions made available in `/ebmlite/util.py`.

### CODE REVIEW

**Comment by StokesMIDE** [comment]
Does this need the changes in #46?

**Comment by CrepeGoat** [comment]
Atm these tests currently fails. Specifically, the tests are running `ebml2xml` and `xml2ebml` on the contents on "tests/video-1.mkv". I generated and git-commit `video-1.xml` using `ebml2xml`, but for some reason when using `xml2ebml` the output is notably different from the original `video-1.mkv` file.

Not sure how to fix atm, but I don't have time to figure out what's wrong either. Any insight is appreciated.

**Comment by CrepeGoat** [comment]
@StokesMIDE good question. These tests are meant to be merged in **before #46** to provide a baseline of verified functionality. Afterwards, we can merge the updated development into #46, update the tests, and if everything is functioning correctly the tests should still pass.

**Comment by StokesMIDE** [comment]
> Atm these tests currently fails. Specifically, the tests are running `ebml2xml` and `xml2ebml` on the contents on "tests/video-1.mkv". I generated and git-commit `video-1.xml` using `ebml2xml`, but for some reason when using `xml2ebml` the output is notably different from the original `video-1.mkv` file.
> 
> Not sure how to fix atm, but I don't have time to figure out what's wrong either. Any insight is appreciated.

Is the output bad, or just different? If `ebmlite` didn't encode the original, there's no guarantee a re-encoded version will match, even if both files are valid. The source file could have done things like encode element sizes with a fixed number of bytes (e.g., to make structures byte align).

Instead of using `filecmp`, you might need to do a 'manual' crawl of the EBML, checking the value of elements against each other. Alternatively, use a test MKV run through a known good version of `ebmlite` (if the file wasn't generated by it already).

**Comment by CrepeGoat** [comment]
welp... 39877810d7e15a784c3b19e767ce8f0df2004519 worked on my machine T-T

**Review by StokesMIDE — APPROVED** [review]

**Pull request merged**
