### PR TITLE
Feature/76 xml codecs

### PR DESCRIPTION
**Pull request by StokesMIDE**
As per #76: XML encoding can now use various means of rendering binary data.

### CODE REVIEW

**Comment by pscheidler** [comment]
Looks very useful, thanks!
Would be great to have the argparser info list out the available encodings

**Comment by StokesMIDE** [comment]
> Looks very useful, thanks! Would be great to have the argparser info list out the available encodings

`ebml2xml -h` will list the names of the codecs. I've now added something to dynamically build a list of descriptions.

**Comment by CFlaniganMide** [comment]
This feels like it could be really useful for the custom IDE file generation that's been brought up in other places.  The way I hacked together one of the other files was by editing it as an xml file.

**Comment by CFlaniganMide** [comment]
I think adding a `BinaryCodec` abstract base class might be helpful.  I can imagine `IDElib` specifically implementing a subclass of `BinaryCodec` that formats elements based on human readability/editablity based on exactly what the type of element is.

**Comment by StokesMIDE** [comment]
> I think adding a `BinaryCodec` abstract base class might be helpful. I can imagine `IDElib` specifically implementing a subclass of `BinaryCodec` that formats elements based on human readability/editablity based on exactly what the type of element is.

Good point. An abstract base class had crossed my mind, but I wasn't sure if it was overengineering. I may want to attach default codecs to element classes themselves in the future, but this would be the first step in any case.

**Comment by StokesMIDE** [comment]
Changing this to a 'real' PR, now that the codecs have the bare minimum of tests.

**Review by CFlaniganMide — APPROVED** [review]
looks good, works on my machine.

**Review by CFlaniganMide — APPROVED** [review]
Changes since last review also look good

**Pull request merged**
